"use client";

import React, { createContext, useContext, useState, useEffect } from "react";

export type SupportedLanguage = "English" | "Hindi" | "Hinglish" | "Tamil" | "Bengali";

interface LanguageContextType {
  language: SupportedLanguage;
  setLanguage: (lang: SupportedLanguage) => void;
  t: (key: string) => string;
}

const translations: Record<SupportedLanguage, Record<string, string>> = {
  English: {
    // Nav & Brand
    "app.title": "Bharat Academix",
    "app.subtitle": "AI Teacher",
    "nav.dashboard": "Dashboard",
    "nav.new_lesson": "New Lesson",
    "nav.history": "Learning History",
    "nav.settings": "Settings",
    "user.role": "Standard Learner",

    // Dashboard
    "dash.welcome": "Welcome back",
    "dash.mastered": "Mastered",
    "dash.to_revise": "To Revise",
    "dash.cta_badge": "Autonomous Adaptive Teacher",
    "dash.cta_title": "What do you want to master today?",
    "dash.cta_desc": "Upload study material or enter any topic. Our AI Teacher will structure a pacing-conscious lesson, explain with an animated avatar & live whiteboard, and dynamically adapt to your answers.",
    "dash.cta_btn": "Start a New Lesson",
    "dash.continue_learning": "Continue Learning",
    "dash.resume_class": "Resume Class",
    "dash.curriculum_rec": "Curriculum Path Recommendation",
    "dash.recent_lessons": "Recent Lessons",
    "dash.no_lessons": "No lessons completed yet.",
    "dash.create_first": "Create your first lesson →",
    "dash.view": "View",

    // Create Lesson
    "create.step": "Step 1 of 3",
    "create.title": "What do you want to learn today?",
    "create.subtitle": "Choose whether to upload existing documents or enter any topic to explore.",
    "create.upload_title": "Upload Material",
    "create.upload_desc": "Upload PDF, Word (DOCX), PowerPoint (PPTX), or Notes for grounded RAG teaching.",
    "create.topic_title": "Enter a Topic",
    "create.topic_desc": "Tell the AI teacher any concept or subject you want to master from scratch.",
    "create.drag_drop": "Drag and drop your file here, or",
    "create.browse": "browse files",
    "create.supported_formats": "Supported: PDF, DOCX, PPTX, TXT, MD (Max 25 MB)",
    "create.topic_label": "Topic or Subject",
    "create.topic_placeholder": "e.g. Ohm's Law, Machine Learning, Newton's Laws...",
    "create.popular_topics": "Or pick a popular subject topic:",
    "create.continue_btn": "Continue to Personalization",

    // Profile Form
    "profile.step": "Step 2 of 3",
    "profile.title": "Tell me about you",
    "profile.mastery_level": "Current Mastery Level",
    "profile.time_budget": "Available Time Budget",
    "profile.teaching_lang": "Teaching Language",
    "profile.customize_style": "Personalize teaching style & background (Optional)",
    "profile.start_lesson_btn": "Start My Lesson",
    "profile.planning": "Planning Your Lesson...",

    // Lesson Plan Preview
    "plan.structure": "Lesson Structure",
    "plan.subtitle": "Review and customize your curriculum timeline before starting the class.",
    "plan.total_budget": "Total",
    "plan.requested": "min requested",
    "plan.ready_prompt": "Ready to enter your AI Classroom?",
    "plan.ready_desc": "The teacher avatar, voice synthesis, whiteboard visualizer, and adaptive checks are prepared.",
    "plan.start_class_btn": "Looks Good, Start Class",

    // Classroom
    "class.concept": "Concept",
    "class.of": "of",
    "class.speaking_script": "Spoken Teaching Script",
    "class.listening": "Listening",
    "class.explaining": "Explaining concept...",
    "class.analyzing": "Analyzing student answer...",
    "class.checking_answer": "Checking answer...",
    "class.submit_answer": "Submit Answer",
    "class.not_sure": "I'm not sure",
    "class.correct_title": "Excellent! That's conceptually accurate.",
    "class.continue_lesson": "Continue Lesson",
    "class.misconception_title": "Let's look at this differently",
    "class.analogy_title": "Alternative Mental Model / Analogy",
    "class.explain_again": "Explain Again with New Analogy",
    "class.try_followup": "Try Follow-up Question",
    "class.exit_confirm": "Exit AI Classroom?",
    "class.exit_desc": "Your lesson state, answered questions, and concept mastery are saved.",
    "class.cancel": "Cancel",
    "class.exit_dashboard": "Exit to Dashboard",

    // Assessment & Report
    "exam.title": "Final Check",
    "exam.question": "Question",
    "exam.previous": "Previous",
    "exam.next": "Next Question",
    "exam.review": "Review Answers",
    "exam.submit": "Submit Assessment",
    "report.title": "Learning Diagnostic Report",
    "report.mastered_concepts": "Mastered Concepts",
    "report.needs_improvement": "Coaching & Revision Focus",
    "report.next_step": "AI Predicted Learning Pathway",
    "report.start_topic": "Start This Topic",
    "report.full_breakdown": "Full Assessment Question Breakdown",
    "report.back_dashboard": "Back to Dashboard",
    "report.retake": "Retake Assessment",

    // Settings
    "settings.title": "Settings & System Preferences",
    "settings.subtitle": "Configure student profile, AI model tiers, and account data.",
    "settings.student_profile": "Student Profile",
    "settings.display_name": "Display Name",
    "settings.default_lang": "Default Language",
    "settings.default_level": "Default Level",
    "settings.model_tiers": "Active Claude Model Tiers",
    "settings.save": "Save Profile",
    "settings.danger_zone": "Danger Zone",
    "settings.clear_data": "Clear Learning History"
  },

  Hindi: {
    // Nav & Brand
    "app.title": "भारत एकेडेमिक्स",
    "app.subtitle": "एआई शिक्षक",
    "nav.dashboard": "डैशबोर्ड",
    "nav.new_lesson": "नया पाठ शुरू करें",
    "nav.history": "सीखने का इतिहास",
    "nav.settings": "सेटिंग्स",
    "user.role": "विद्यार्थी",

    // Dashboard
    "dash.welcome": "वापसी पर स्वागत है",
    "dash.mastered": "पूर्ण रूप से सीखा",
    "dash.to_revise": "दोहराने योग्य",
    "dash.cta_badge": "स्वायत्त अनुकूली एआई शिक्षक",
    "dash.cta_title": "आज आप क्या सीखना चाहते हैं?",
    "dash.cta_desc": "अपनी अध्ययन सामग्री अपलोड करें या कोई भी विषय दर्ज करें। हमारा एआई शिक्षक एक व्यक्तिगत पाठ तैयार करेगा, एनिमेटेड अवतार और लाइव व्हाइटबोर्ड से समझाएगा और आपके उत्तरों के अनुसार खुद को ढालेगा।",
    "dash.cta_btn": "नया पाठ शुरू करें",
    "dash.continue_learning": "पढ़ाई जारी रखें",
    "dash.resume_class": "कक्षा फिर से शुरू करें",
    "dash.curriculum_rec": "सुझाई गई अगली शिक्षण राह",
    "dash.recent_lessons": "हाल के पाठ",
    "dash.no_lessons": "अभी तक कोई पाठ पूरा नहीं हुआ है।",
    "dash.create_first": "अपना पहला पाठ बनाएं →",
    "dash.view": "देखें",

    // Create Lesson
    "create.step": "चरण 1 / 3",
    "create.title": "आज आप क्या सीखना चाहते हैं?",
    "create.subtitle": "दस्तावेज़ अपलोड करें या सीधे किसी भी विषय का नाम दर्ज करें।",
    "create.upload_title": "सामग्री अपलोड करें",
    "create.upload_desc": "सटीक संदर्भ के लिए PDF, Word (DOCX), PowerPoint (PPTX) या नोट्स अपलोड करें।",
    "create.topic_title": "विषय दर्ज करें",
    "create.topic_desc": "एआई शिक्षक को कोई भी विषय बताएं जिसे आप शुरू से सीखना चाहते हैं।",
    "create.drag_drop": "अपनी फ़ाइल यहाँ खींचें और छोड़ें, या",
    "create.browse": "फ़ाइलें चुनें",
    "create.supported_formats": "समर्थित प्रारूप: PDF, DOCX, PPTX, TXT, MD (अधिकतम 25 MB)",
    "create.topic_label": "विषय का नाम",
    "create.topic_placeholder": "उदा. ओम का नियम, मशीन लर्निंग, न्यूटन के नियम...",
    "create.popular_topics": "या इनमें से कोई लोकप्रिय विषय चुनें:",
    "create.continue_btn": "प्राथमिकताएं सेट करें",

    // Profile Form
    "profile.step": "चरण 2 / 3",
    "profile.title": "अपनी प्राथमिकताओं के बारे में बताएं",
    "profile.mastery_level": "वर्तमान दक्षता स्तर",
    "profile.time_budget": "उपलब्ध समय सीमा",
    "profile.teaching_lang": "पढ़ाने की भाषा",
    "profile.customize_style": "पढ़ाने की शैली और पूर्व ज्ञान चुनें (वैकल्पिक)",
    "profile.start_lesson_btn": "मेरा पाठ शुरू करें",
    "profile.planning": "पाठ की योजना बन रही है...",

    // Lesson Plan Preview
    "plan.structure": "पाठ की रूपरेखा",
    "plan.subtitle": "कक्षा शुरू करने से पहले अपनी समय-सीमा और विषयों की समीक्षा करें।",
    "plan.total_budget": "कुल समय",
    "plan.requested": "मिनट निर्धारित",
    "plan.ready_prompt": "क्या आप अपनी एआई कक्षा में प्रवेश करने के लिए तैयार हैं?",
    "plan.ready_desc": "शिक्षक अवतार, वाक् संश्लेषण, व्हाइटबोर्ड और अनुकूली प्रश्न तैयार हैं।",
    "plan.start_class_btn": "कक्षा शुरू करें",

    // Classroom
    "class.concept": "संकल्पना",
    "class.of": "/",
    "class.speaking_script": "शिक्षक का मौखिक विवरण",
    "class.listening": "सुन रहा है",
    "class.explaining": "संकल्पना समझा रहे हैं...",
    "class.analyzing": "उत्तर का विश्लेषण हो रहा है...",
    "class.checking_answer": "उत्तर जांचा जा रहा है...",
    "class.submit_answer": "उत्तर सबमिट करें",
    "class.not_sure": "मुझे पक्का नहीं पता",
    "class.correct_title": "उत्कृष्ट! आपका उत्तर बिल्कुल सही है।",
    "class.continue_lesson": "पाठ आगे बढ़ाएं",
    "class.misconception_title": "आइए इसे एक अलग दृष्टिकोण से समझें",
    "class.analogy_title": "वैकल्पिक उदाहरण / नया मॉडल",
    "class.explain_again": "नए उदाहरण के साथ पुनः समझाएं",
    "class.try_followup": "अनुवर्ती प्रश्न हल करें",
    "class.exit_confirm": "कक्षा से बाहर निकलें?",
    "class.exit_desc": "आपकी प्रगति और सीखे गए विषय सुरक्षित हैं। आप कभी भी वापस आ सकते हैं।",
    "class.cancel": "रद्द करें",
    "class.exit_dashboard": "डैशबोर्ड पर जाएं",

    // Assessment & Report
    "exam.title": "अंतिम मूल्यांकन",
    "exam.question": "प्रश्न",
    "exam.previous": "पिछला",
    "exam.next": "अगला प्रश्न",
    "exam.review": "उत्तरों की समीक्षा करें",
    "exam.submit": "मूल्यांकन सबमिट करें",
    "report.title": "अधिगम निदान रिपोर्ट",
    "report.mastered_concepts": "पूर्णतः सीखे गए विषय",
    "report.needs_improvement": "पुनरावृत्ति एवं सुधार हेतु",
    "report.next_step": "सुझाया गया अगला विषय",
    "report.start_topic": "यह विषय शुरू करें",
    "report.full_breakdown": "सभी प्रश्नों का विस्तृत विवरण",
    "report.back_dashboard": "डैशबोर्ड पर लौटें",
    "report.retake": "पुनः परीक्षा दें",

    // Settings
    "settings.title": "सेटिंग्स और सिस्टम प्राथमिकताएं",
    "settings.subtitle": "विद्यार्थी प्रोफ़ाइल, एआई मॉडल टियर और डेटा प्रबंधित करें।",
    "settings.student_profile": "विद्यार्थी प्रोफ़ाइल",
    "settings.display_name": "प्रदर्शित नाम",
    "settings.default_lang": "डिफ़ॉल्ट भाषा",
    "settings.default_level": "डिफ़ॉल्ट स्तर",
    "settings.model_tiers": "सक्रिय क्लॉड मॉडल टियर",
    "settings.save": "प्रोफ़ाइल सुरक्षित करें",
    "settings.danger_zone": "डेटा रीसेट क्षेत्र",
    "settings.clear_data": "सीखने का इतिहास साफ़ करें"
  },

  Hinglish: {
    // Nav & Brand
    "app.title": "Bharat Academix",
    "app.subtitle": "AI Teacher",
    "nav.dashboard": "Dashboard",
    "nav.new_lesson": "New Lesson",
    "nav.history": "Learning History",
    "nav.settings": "Settings",
    "user.role": "Student",

    // Dashboard
    "dash.welcome": "Welcome back",
    "dash.mastered": "Mastered",
    "dash.to_revise": "Revise Karna Hai",
    "dash.cta_badge": "Autonomous Adaptive AI Teacher",
    "dash.cta_title": "Aaj aap kya master karna chahte hain?",
    "dash.cta_desc": "Apna study material upload karein ya koi bhi topic enter karein. Humara AI Teacher structured pacing ke sath live whiteboard aur animated avatar se sikhayega.",
    "dash.cta_btn": "Start a New Lesson",
    "dash.continue_learning": "Continue Learning",
    "dash.resume_class": "Class Resume Karein",
    "dash.curriculum_rec": "Recommended Next Learning Path",
    "dash.recent_lessons": "Recent Lessons",
    "dash.no_lessons": "Abhi tak koi lesson complete nahi hua.",
    "dash.create_first": "Apna pehla lesson banayein →",
    "dash.view": "View",

    // Create Lesson
    "create.step": "Step 1 of 3",
    "create.title": "Aaj aap kya sikhna chahte hain?",
    "create.subtitle": "Documents upload karein ya direct kisi topic ka naam enter karein.",
    "create.upload_title": "Upload Material",
    "create.upload_desc": "PDF, DOCX, PPTX ya notes upload karein RAG grounded teaching ke liye.",
    "create.topic_title": "Enter a Topic",
    "create.topic_desc": "AI teacher ko batayein jo bhi concept aap zero se sikhna chahte hain.",
    "create.drag_drop": "File yahan drag & drop karein, ya",
    "create.browse": "browse karein",
    "create.supported_formats": "Supported formats: PDF, DOCX, PPTX, TXT, MD (Max 25 MB)",
    "create.topic_label": "Topic ya Subject",
    "create.topic_placeholder": "e.g. Ohm's Law, Machine Learning, Newton's Laws...",
    "create.popular_topics": "Ya popular topic choose karein:",
    "create.continue_btn": "Preferences Set Karein",

    // Profile Form
    "profile.step": "Step 2 of 3",
    "profile.title": "Apne bare me batayein",
    "profile.mastery_level": "Current Mastery Level",
    "profile.time_budget": "Available Time Budget",
    "profile.teaching_lang": "Teaching Language",
    "profile.customize_style": "Style & Background customize karein (Optional)",
    "profile.start_lesson_btn": "Start My Lesson",
    "profile.planning": "Lesson plan generate ho raha hai...",

    // Lesson Plan Preview
    "plan.structure": "Lesson Plan Preview",
    "plan.subtitle": "Class start karne se pehle curriculum timeline check karein.",
    "plan.total_budget": "Total Time",
    "plan.requested": "min planned",
    "plan.ready_prompt": "AI Classroom enter karne ke liye ready hain?",
    "plan.ready_desc": "Avatar, speech, whiteboard visualizer aur adaptive checks ready hain.",
    "plan.start_class_btn": "Looks Good, Start Class",

    // Classroom
    "class.concept": "Concept",
    "class.of": "of",
    "class.speaking_script": "Teacher Spoken Script",
    "class.listening": "Listening",
    "class.explaining": "Concept explain ho raha hai...",
    "class.analyzing": "Student answer analyze ho raha hai...",
    "class.checking_answer": "Answer check ho raha hai...",
    "class.submit_answer": "Submit Answer",
    "class.not_sure": "Mujhe sure nahi pata",
    "class.correct_title": "Shabash! Aapka concept bilkul accurate hai.",
    "class.continue_lesson": "Next Concept Par Chalein",
    "class.misconception_title": "Chaliye isko dusre tarike se dekhte hain",
    "class.analogy_title": "Alternative Real-Life Analogy",
    "class.explain_again": "New Analogy Ke Saath Re-Explain Karein",
    "class.try_followup": "Follow-up Question Try Karein",
    "class.exit_confirm": "Classroom se exit karein?",
    "class.exit_desc": "Aapki progress and mastered concepts saved hain.",
    "class.cancel": "Cancel",
    "class.exit_dashboard": "Dashboard Par Jayein",

    // Assessment & Report
    "exam.title": "Final Check Assessment",
    "exam.question": "Question",
    "exam.previous": "Previous",
    "exam.next": "Next Question",
    "exam.review": "Answers Review Karein",
    "exam.submit": "Submit Assessment",
    "report.title": "Learning Diagnostic Report",
    "report.mastered_concepts": "Mastered Concepts",
    "report.needs_improvement": "Revision Focus Areas",
    "report.next_step": "Recommended Next Pathway",
    "report.start_topic": "Start This Topic",
    "report.full_breakdown": "Full Question Breakdown",
    "report.back_dashboard": "Back to Dashboard",
    "report.retake": "Retake Exam",

    // Settings
    "settings.title": "Settings & Preferences",
    "settings.subtitle": "Profile aur model tiers manage karein.",
    "settings.student_profile": "Student Profile",
    "settings.display_name": "Display Name",
    "settings.default_lang": "Default Language",
    "settings.default_level": "Default Level",
    "settings.model_tiers": "Active Claude Model Tiers",
    "settings.save": "Profile Save Karein",
    "settings.danger_zone": "Danger Zone",
    "settings.clear_data": "Learning History Clear Karein"
  },

  Tamil: {
    "app.title": "பாரத் அகாடமிக்ஸ்",
    "app.subtitle": "AI ஆசிரியர்",
    "nav.dashboard": "முகப்புப்பலகை",
    "nav.new_lesson": "புதிய பாடம்",
    "nav.history": "கற்றல் வரலாறு",
    "nav.settings": "அமைப்புகள்",
    "user.role": "மாணவர்",
    "dash.welcome": "மீண்டும் நல்வரவு",
    "dash.mastered": "தேர்ச்சி பெற்றது",
    "dash.to_revise": "மீள்பார்வை செய்ய",
    "dash.cta_badge": "தன்னாட்சி அடாப்டிவ் AI ஆசிரியர்",
    "dash.cta_title": "இன்று நீங்கள் எதைக் கற்க விரும்புகிறீர்கள்?",
    "dash.cta_desc": "பாடக்குறிப்புகளைப் பதிவேற்றவும் அல்லது புதிய தலைப்பை உள்ளிடவும். எங்களின் AI ஆசிரியர் உயிரோட்டமான ஆசிரியர் மற்றும் வைட்போர்டு மூலம் கற்பிப்பார்.",
    "dash.cta_btn": "புதிய பாடத்தைத் தொடங்கு",
    "dash.continue_learning": "கற்றலைத் தொடரவும்",
    "dash.resume_class": "வகுப்பை மீண்டும் தொடரவும்",
    "dash.curriculum_rec": "பரிந்துரைக்கப்பட்ட பாடத்திட்டம்",
    "dash.recent_lessons": "சமீபத்திய பாடங்கள்",
    "dash.no_lessons": "பாடங்கள் எதுவும் இன்னும் முடிக்கப்படவில்லை.",
    "dash.create_first": "உங்கள் முதல் பாடத்தை உருவாக்குங்கள் →",
    "dash.view": "பார்வை",
    "create.step": "படி 1 / 3",
    "create.title": "இன்று என்ன கற்க விரும்புகிறீர்கள்?",
    "create.subtitle": "ஆவணங்களைப் பதிவேற்றவும் அல்லது தலைப்பை நேரடியாக உள்ளிடவும்.",
    "create.upload_title": "பாடப்பொருளைப் பதிவேற்றவும்",
    "create.upload_desc": "PDF, DOCX, PPTX அல்லது குறிப்புகளைப் பதிவேற்றவும்.",
    "create.topic_title": "தலைப்பை உள்ளிடவும்",
    "create.topic_desc": "நீங்கள் கற்றுக்கொள்ள விரும்பும் எந்தவொரு தலைப்பையும் AI ஆசிரியரிடம் கூறவும்.",
    "create.drag_drop": "கோப்பை இங்கே இழுத்துப் போடவும், அல்லது",
    "create.browse": "கோப்புகளைத் தேர்ந்தெடுக்கவும்",
    "create.supported_formats": "ஆதரிக்கப்படும் வடிவங்கள்: PDF, DOCX, PPTX, TXT, MD (Max 25 MB)",
    "create.topic_label": "தலைப்பு அல்லது பாடம்",
    "create.topic_placeholder": "எ.கா. ஓம் விதி, இயந்திரக் கற்றல், நியூட்டன் விதிகள்...",
    "create.popular_topics": "அல்லது பிரபலமான தலைப்பைத் தேர்ந்தெடுக்கவும்:",
    "create.continue_btn": "தொடரவும்",
    "profile.step": "படி 2 / 3",
    "profile.title": "உங்கள் விவரங்கள்",
    "profile.mastery_level": "தற்போதைய நிலை",
    "profile.time_budget": "கிடைக்கும் நேரம்",
    "profile.teaching_lang": "கற்பிக்கும் மொழி",
    "profile.customize_style": "கற்பித்தல் பாணியைத் தனிப்பயனாக்குங்கள்",
    "profile.start_lesson_btn": "பாடத்தைத் தொடங்கு",
    "profile.planning": "பாடம் திட்டமிடப்படுகிறது...",
    "plan.structure": "பாடத் திட்டம்",
    "plan.subtitle": "வகுப்பைத் தொடங்குவதற்கு முன் பாடத்திட்டத்தை மதிப்பாய்வு செய்யவும்.",
    "plan.total_budget": "மொத்த நேரம்",
    "plan.requested": "நிமிடங்கள்",
    "plan.ready_prompt": "AI வகுப்பறையில் நுழைய தயாரா?",
    "plan.ready_desc": "ஆசிரியர் அவதார், குரல் மற்றும் வைட்போர்டு தயாராக உள்ளன.",
    "plan.start_class_btn": "வகுப்பைத் தொடங்கு",
    "class.concept": "கருத்து",
    "class.of": "இல்",
    "class.speaking_script": "ஆசிரியரின் உரை",
    "class.listening": "கேட்கிறது",
    "class.explaining": "விளக்குகிறது...",
    "class.analyzing": "பதிலை ஆய்வு செய்கிறது...",
    "class.checking_answer": "பதிலைச் சரிபார்க்கிறது...",
    "class.submit_answer": "பதிலைச் சமர்ப்பிக்கவும்",
    "class.not_sure": "எனக்குத் தெரியவில்லை",
    "class.correct_title": "அருமை! உங்கள் கருத்து சரியானது.",
    "class.continue_lesson": "பாடத்தைத் தொடரவும்",
    "class.misconception_title": "இதை வேறு விதமாகப் பார்ப்போம்",
    "class.analogy_title": "மாற்று உதாரணம் / ஒப்பீடு",
    "class.explain_again": "புதிய உதாரணத்துடன் மீண்டும் விளக்குக",
    "class.try_followup": "அடுத்த கேள்வியை முயற்சிக்கவும்",
    "class.exit_confirm": "வகுப்பறையிலிருந்து வெளியேறவா?",
    "class.exit_desc": "உங்கள் முன்னேற்றம் பாதுகாப்பாகச் சேமிக்கப்பட்டுள்ளது.",
    "class.cancel": "ரத்துசெய்",
    "class.exit_dashboard": "முகப்புப்பலகைக்குச் செல்",
    "exam.title": "இறுதி மதிப்பீடு",
    "exam.question": "கேள்வி",
    "exam.previous": "முந்தைய",
    "exam.next": "அடுத்த கேள்வி",
    "exam.review": "பதில்களை மதிப்பாய்வு செய்க",
    "exam.submit": "மதிப்பீட்டைச் சமர்ப்பிக்கவும்",
    "report.title": "கற்றல் அறிக்கை",
    "report.mastered_concepts": "தேர்ச்சி பெற்ற கருத்துக்கள்",
    "report.needs_improvement": "மேம்படுத்த வேண்டியவை",
    "report.next_step": "பரிந்துரைக்கப்பட்ட அடுத்த தலைப்பு",
    "report.start_topic": "இந்தத் தலைப்பைத் தொடங்கு",
    "report.full_breakdown": "முழுமையான விளக்கம்",
    "report.back_dashboard": "முகப்புப்பலகைக்குத் திரும்பு",
    "report.retake": "மீண்டும் தேர்வு எழுது",
    "settings.title": "அமைப்புகள்",
    "settings.subtitle": "சுயவிவரம் மற்றும் அமைப்புகளை நிர்வகிக்கவும்.",
    "settings.student_profile": "மாணவர் சுயவிவரம்",
    "settings.display_name": "பெயர்",
    "settings.default_lang": "இயல்புநிலை மொழி",
    "settings.default_level": "இயல்புநிலை நிலை",
    "settings.model_tiers": "AI மாதிரி நிலைகள்",
    "settings.save": "சேமி",
    "settings.danger_zone": "தரவு மீட்டமைப்பு",
    "settings.clear_data": "வரலாற்றை அழிக்கவும்"
  },

  Bengali: {
    "app.title": "ভারত অ্যাকাডেমিক্স",
    "app.subtitle": "AI শিক্ষক",
    "nav.dashboard": "ড্যাশবোর্ড",
    "nav.new_lesson": "নতুন পাঠ",
    "nav.history": "শেখার ইতিহাস",
    "nav.settings": "সেটিংস",
    "user.role": "শিক্ষার্থী",
    "dash.welcome": "স্বাগতম",
    "dash.mastered": "দক্ষতা অর্জন",
    "dash.to_revise": "পুনরাবৃত্তি প্রয়োজন",
    "dash.cta_badge": "স্বায়ত্তশাসিত অ্যাডাপ্টিভ AI শিক্ষক",
    "dash.cta_title": "আজ আপনি কী শিখতে চান?",
    "dash.cta_desc": "আপনার অধ্যয়নের উপাদান আপলোড করুন বা যেকোনো বিষয় লিখুন। আমাদের AI শিক্ষক অ্যানিমেটেড অবতার এবং লাইভ হোয়াইটবোর্ডের মাধ্যমে শেখাবেন।",
    "dash.cta_btn": "নতুন পাঠ শুরু করুন",
    "dash.continue_learning": "শেখা চালিয়ে যান",
    "dash.resume_class": "ক্লাস পুনরায় শুরু করুন",
    "dash.curriculum_rec": "প্রস্তাবিত পাঠ্যক্রম",
    "dash.recent_lessons": "সাম্প্রতিক পাঠ",
    "dash.no_lessons": "এখনও কোনো পাঠ সম্পন্ন হয়নি।",
    "dash.create_first": "আপনার প্রথম পাঠ তৈরি করুন →",
    "dash.view": "দেখুন",
    "create.step": "পদক্ষেপ ১ / ৩",
    "create.title": "আজ আপনি কী শিখতে চান?",
    "create.subtitle": "নথি আপলোড করুন অথবা সরাসরি একটি বিষয় লিখুন।",
    "create.upload_title": "উপাদান আপলোড করুন",
    "create.upload_desc": "PDF, DOCX, PPTX বা নোট আপলোড করুন।",
    "create.topic_title": "বিষয় লিখুন",
    "create.topic_desc": "আপনি যা শিখতে চান তা AI শিক্ষককে বলুন।",
    "create.drag_drop": "ফাইল এখানে টেনে আনুন, অথবা",
    "create.browse": "ফাইল ব্রাউজ করুন",
    "create.supported_formats": "সমর্থিত ফরম্যাট: PDF, DOCX, PPTX, TXT, MD (Max 25 MB)",
    "create.topic_label": "বিষয়",
    "create.topic_placeholder": "যেমন: ওহমের সূত্র, মেশিন লার্নিং, নিউটনের সূত্র...",
    "create.popular_topics": "অথবা জনপ্রিয় বিষয় নির্বাচন করুন:",
    "create.continue_btn": "এগিয়ে যান",
    "profile.step": "পদক্ষেপ ২ / ৩",
    "profile.title": "আপনার বিবরণ",
    "profile.mastery_level": "বর্তমান স্তর",
    "profile.time_budget": "উপলব্ধ সময়",
    "profile.teaching_lang": "শিক্ষাদানের ভাষা",
    "profile.customize_style": "শিক্ষাদান শৈলী কাস্টমাইজ করুন",
    "profile.start_lesson_btn": "পাঠ শুরু করুন",
    "profile.planning": "পাঠ পরিকল্পনা করা হচ্ছে...",
    "plan.structure": "পাঠের কাঠামো",
    "plan.subtitle": "ক্লাস শুরু করার আগে পাঠ্যক্রম পর্যালোচনা করুন।",
    "plan.total_budget": "মোট সময়",
    "plan.requested": "মিনিট",
    "plan.ready_prompt": "AI ক্লাসরুমে প্রবেশ করতে প্রস্তুত?",
    "plan.ready_desc": "শিক্ষক অবতার, কণ্ঠস্বর এবং হোয়াইটবোর্ড প্রস্তুত।",
    "plan.start_class_btn": "ক্লাস শুরু করুন",
    "class.concept": "ধারণা",
    "class.of": "এর মধ্যে",
    "class.speaking_script": "শিক্ষকের কথ্য স্ক্রিপ্ট",
    "class.listening": "শুনছে",
    "class.explaining": "ব্যাখ্যা করছে...",
    "class.analyzing": "উত্তর বিশ্লেষণ করছে...",
    "class.checking_answer": "উত্তর যাচাই করছে...",
    "class.submit_answer": "উত্তর জমা দিন",
    "class.not_sure": "আমি নিশ্চিত নই",
    "class.correct_title": "চমৎকার! আপনার ধারণা সঠিক।",
    "class.continue_lesson": "পাঠ চালিয়ে যান",
    "class.misconception_title": "চলুন এটি ভিন্নভাবে দেখি",
    "class.analogy_title": "বিকল্প উদাহরণ / সাদৃশ্য",
    "class.explain_again": "নতুন উদাহরণ সহ পুনরায় ব্যাখ্যা করুন",
    "class.try_followup": "পরবর্তী প্রশ্ন চেষ্টা করুন",
    "class.exit_confirm": "ক্লাসরুম থেকে বের হবেন?",
    "class.exit_desc": "আপনার অগ্রগতির বিবরণ নিরাপদে সংরক্ষিত আছে।",
    "class.cancel": "বাতিল",
    "class.exit_dashboard": "ড্যাশবোর্ডে ফিরে যান",
    "exam.title": "চূড়ান্ত মূল্যায়ন",
    "exam.question": "প্রশ্ন",
    "exam.previous": "পূর্ববর্তী",
    "exam.next": "পরবর্তী প্রশ্ন",
    "exam.review": "উত্তর পর্যালোচনা করুন",
    "exam.submit": "মূল্যায়ন জমা দিন",
    "report.title": "শিক্ষণ রোগ নির্ণয় রিপোর্ট",
    "report.mastered_concepts": "অর্জিত দক্ষতাসমূহ",
    "report.needs_improvement": "উন্নতির ক্ষেত্রসমূহ",
    "report.next_step": "প্রস্তাবিত পরবর্তী বিষয়",
    "report.start_topic": "এই বিষয় শুরু করুন",
    "report.full_breakdown": "সম্পূর্ণ বিবরণ",
    "report.back_dashboard": "ড্যাশবোর্ডে ফিরে যান",
    "report.retake": "পুনরায় পরীক্ষা দিন",
    "settings.title": "সেটিংস",
    "settings.subtitle": "প্রোফাইল এবং পছন্দসমূহ পরিচালনা করুন।",
    "settings.student_profile": "শিক্ষার্থীর প্রোফাইল",
    "settings.display_name": "নাম",
    "settings.default_lang": "ডিফল্ট ভাষা",
    "settings.default_level": "ডিফল্ট স্তর",
    "settings.model_tiers": "AI মডেল স্তর",
    "settings.save": "সংরক্ষণ করুন",
    "settings.danger_zone": "ডেটা রিসেট",
    "settings.clear_data": "ইতিহাস মুছুন"
  }
};

const LanguageContext = createContext<LanguageContextType>({
  language: "English",
  setLanguage: () => {},
  t: (key: string) => key,
});

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<SupportedLanguage>("English");

  useEffect(() => {
    const saved = localStorage.getItem("app_language") as SupportedLanguage;
    if (saved && ["English", "Hindi", "Hinglish", "Tamil", "Bengali"].includes(saved)) {
      setLanguageState(saved);
    }
  }, []);

  const setLanguage = (lang: SupportedLanguage) => {
    setLanguageState(lang);
    if (typeof window !== "undefined") {
      localStorage.setItem("app_language", lang);
    }
  };

  const t = (key: string): string => {
    const currentDict = translations[language] || translations["English"];
    return currentDict[key] || translations["English"][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);
